CREATE SCHEMA IF NOT EXISTS accounts;
SET SCHEMA accounts;

CREATE TABLE IF NOT EXISTS accounts(
  id BIGINT IDENTITY,
  name VARCHAR NOT NULL,
  balance DECIMAL(20,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS transactions(
  id BIGINT IDENTITY,
  from_acc BIGINT,
  to_acc BIGINT,
  amount DECIMAL(20,2) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);